remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
title: Guitar Starter Pack
color_scheme: dark

# logo: "/assets/intro.excalidraw.svg"
favicon_ico: "/assets/guitar.excalidraw.svg"
aux_links:
  "GitHub":
    - "//github.com/Sydekends/Guitarisation"

aux_links_new_tab: true


nav_external_links:
  - title : LightNote
    url : https://www.lightnote.co
  - title: Theory mt21c
    url: https://musictheory.pugetsound.edu
  - title : muted.io
    url: https://muted.io
  - title : Chromatone
    url : https://chromatone.center
  - title : Simplifyingtheory
    url : https://www.simplifyingtheory.com
  - title: Advancing Music Theory
    url: https://tobyrush.com/theorywiki
  - title : FMHY
    url : https://fmhy.net/educational#music