remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
title: Guitar Starter Pack
color_scheme: dark

logo: "/assets/intro.excalidraw.svg"
favicon_ico: "/assets/guitar.excalidraw.svg"
aux_links:
  "GitHub":
    - "//github.com/Sydekends/Guitarisation"

aux_links_new_tab: true


nav_external_links:
  - title : LightNote
    url : //www.lightnote.co
  - title: Theory mt21c
    url: //musictheory.pugetsound.edu
  - title : muted.io
    url: //muted.io
  - title : Chromatone
    url : //chromatone.center
  - title : Simplifyingtheory
    url : //www.simplifyingtheory.com
  - title: Advancing Music Theory
    url: //tobyrush.com/theorywiki
  - title : FMHY
    url : //fmhy.net/educational#music

# "Theory mt21c" :
#   - "//musictheory.pugetsound.edu/"
# "Advancing Music Theory" :
#   - "//tobyrush.com/theorywiki/"